apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golem-gateway
  namespace: golem
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: golem.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golem-gateway
                port:
                  number: 80
